name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag rhafiko/evolutionapi:latest
        docker build . --file Dockerfile --tag rhafiko/evolutionapi:$(date +%s)
        docker push rhafiko/evolutionapi:latest
        docker push rhafiko/evolutionapi:$(date +%s)
